# OCR工作流路由规则配置
# 定义不同条件下的适配器选择策略

# 基础路由规则
routing_rules:
  # 基于任务类型的路由
  task_type:
    document_ocr: "local_model_mcp"           # 通用文档OCR使用本地处理
    handwriting_recognition: "cloud_search_mcp"  # 手写识别使用云端处理
    table_extraction: "local_model_mcp"       # 表格提取使用本地处理
    form_processing: "local_model_mcp"        # 表单处理使用本地处理
    complex_document: "cloud_search_mcp"      # 复杂文档使用云端处理
    multi_language_ocr: "cloud_search_mcp"    # 多语言OCR使用云端处理
  
  # 基于质量级别的路由
  quality_level:
    low: "local_model_mcp"                    # 低质量要求使用本地处理
    medium: "local_model_mcp"                 # 中等质量要求使用本地处理
    high: "cloud_search_mcp"                  # 高质量要求使用云端处理
    ultra_high: "cloud_search_mcp"            # 超高质量要求使用云端处理
  
  # 基于隐私级别的路由
  privacy_level:
    low: "cloud_search_mcp"                   # 低隐私要求可使用云端处理
    normal: "local_model_mcp"                 # 普通隐私要求使用本地处理
    high: "local_model_mcp"                   # 高隐私要求强制本地处理
  
  # 基于文件大小的路由(MB)
  file_size:
    small: "local_model_mcp"                  # 小文件(<5MB)使用本地处理
    medium: "local_model_mcp"                 # 中等文件(5-20MB)使用本地处理
    large: "cloud_search_mcp"                 # 大文件(>20MB)使用云端处理
  
  # 基于语言的路由
  language:
    chinese: "local_model_mcp"                # 中文使用本地处理
    english: "local_model_mcp"                # 英文使用本地处理
    mixed: "cloud_search_mcp"                 # 混合语言使用云端处理
    auto: "local_model_mcp"                   # 自动检测使用本地处理

# 特殊规则 - 强制路由条件
special_rules:
  # 强制使用本地处理的条件
  force_local:
    - condition: "privacy_level"
      value: "high"
      reason: "高隐私要求必须本地处理"
    
    - condition: "file_size_mb"
      operator: "<"
      value: 1
      reason: "小文件优先本地处理"
    
    - condition: "metadata.force_local"
      value: true
      reason: "用户明确要求本地处理"
  
  # 强制使用云端处理的条件
  force_cloud:
    - condition: "quality_level"
      value: "ultra_high"
      reason: "超高质量要求使用云端处理"
    
    - condition: "task_type"
      value: "complex_document"
      reason: "复杂文档需要云端高级算法"
    
    - condition: "file_size_mb"
      operator: ">"
      value: 30
      reason: "大文件使用云端处理"
    
    - condition: "metadata.force_cloud"
      value: true
      reason: "用户明确要求云端处理"

# 决策权重 - 用于综合评分
decision_weights:
  task_type: 0.25          # 任务类型权重
  quality_level: 0.30      # 质量级别权重
  privacy_level: 0.35      # 隐私级别权重(最高权重)
  file_size: 0.10          # 文件大小权重

# 适配器性能配置
adapter_performance:
  local_model_mcp:
    # 本地适配器性能特征
    avg_processing_time: 5.0    # 平均处理时间(秒)
    max_file_size: 20           # 最大文件大小(MB)
    supported_formats: ["jpg", "jpeg", "png", "bmp", "tiff"]
    quality_score: 0.85         # 质量评分
    privacy_score: 1.0          # 隐私评分(最高)
    cost_score: 1.0             # 成本评分(免费)
  
  cloud_search_mcp:
    # 云端适配器性能特征
    avg_processing_time: 3.0    # 平均处理时间(秒)
    max_file_size: 100          # 最大文件大小(MB)
    supported_formats: ["jpg", "jpeg", "png", "bmp", "tiff", "pdf"]
    quality_score: 0.95         # 质量评分(更高)
    privacy_score: 0.6          # 隐私评分(较低)
    cost_score: 0.7             # 成本评分(有费用)

# 负载均衡配置
load_balancing:
  # 是否启用负载均衡
  enabled: true
  
  # 负载均衡策略
  strategy: "weighted_round_robin"  # 加权轮询
  
  # 适配器权重
  weights:
    local_model_mcp: 0.7
    cloud_search_mcp: 0.3
  
  # 健康检查配置
  health_check:
    interval: 60              # 健康检查间隔(秒)
    timeout: 10               # 健康检查超时(秒)
    failure_threshold: 3      # 失败阈值
    recovery_threshold: 2     # 恢复阈值

# 故障转移配置
failover:
  # 是否启用故障转移
  enabled: true
  
  # 故障转移策略
  strategy: "fallback"        # 降级策略
  
  # 故障转移规则
  rules:
    - from: "cloud_search_mcp"
      to: "local_model_mcp"
      conditions:
        - "network_error"
        - "timeout"
        - "service_unavailable"
    
    - from: "local_model_mcp"
      to: "cloud_search_mcp"
      conditions:
        - "resource_exhausted"
        - "model_unavailable"
  
  # 重试配置
  retry:
    max_attempts: 3           # 最大重试次数
    backoff_factor: 2         # 退避因子
    initial_delay: 1          # 初始延迟(秒)

# 缓存策略
caching:
  # 路由决策缓存
  route_cache:
    enabled: true
    ttl: 300                  # 缓存生存时间(秒)
    max_size: 1000            # 最大缓存条目数
  
  # 性能统计缓存
  performance_cache:
    enabled: true
    ttl: 600                  # 缓存生存时间(秒)
    max_size: 100             # 最大缓存条目数

# 监控和告警
monitoring:
  # 性能监控
  performance:
    enabled: true
    metrics:
      - "processing_time"
      - "success_rate"
      - "adapter_usage"
      - "error_rate"
  
  # 告警配置
  alerts:
    # 成功率告警
    success_rate:
      threshold: 0.9          # 成功率阈值
      window: 300             # 监控窗口(秒)
    
    # 处理时间告警
    processing_time:
      threshold: 30           # 处理时间阈值(秒)
      window: 300             # 监控窗口(秒)
    
    # 错误率告警
    error_rate:
      threshold: 0.1          # 错误率阈值
      window: 300             # 监控窗口(秒)

